Bacchus/Bacchus/Controllers/AuctionResultsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Bacchus.DataStorage.Interfaces;
using Bacchus.Domain;
using Bacchus.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Bacchus.Controllers
{
    public class AuctionResultsController : Controller
    {
        private IBidRepository _bidRepo;
        private AuctionsViewModel _viewModel { get; set; } = new AuctionsViewModel();

        public AuctionResultsController(IBidRepository bidRepo)
        {
            _bidRepo = bidRepo;
        }

        public async Task<IActionResult> AuctionResultsView()
        {
            List<User> expiredAuctions = await _bidRepo.GetExpiredBidsAsync();

            if (expiredAuctions != null)
            {
                _viewModel.UserBids = expiredAuctions;
                GetWinnerIdsFromUserBidList(expiredAuctions);
            }

            return View(_viewModel);
        }

        private void GetWinnerIdsFromUserBidList(List<User> userBids)
        {
            List<Guid> result = new List<Guid>();
            List<Guid> productIds = userBids.Select(b => b.Bid.ProductId).Distinct().ToList();

            foreach (var item in productIds)
            {
                var winner = userBids.Where(p => p.Bid.ProductId == item)
                    .OrderByDescending(b=>b.Bid.BidAmount).First();

                result.Add(winner.UserId);
            }

            _viewModel.AuctionWinners = result;
        }
    }
}

Bacchus/Bacchus/Controllers/MyAuctionsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Bacchus.Controllers.Sessions;
using Bacchus.DataStorage.Interfaces;
using Bacchus.Domain;
using Bacchus.RestClient.Interfaces;
using Bacchus.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Bacchus.Controllers
{
    public class MyAuctionsController : Controller
    {
        private IBidRepository _bidRepo;
        private ISessionControl _sessionControl;
        private string _message => "Nothing was found!";

        private AuctionsViewModel _viewModel { get; set; } = new AuctionsViewModel();
        public MyAuctionsController(IBidRepository bidRepo,
            ISessionControl sessionControl)
        {
            _bidRepo = bidRepo;
            _sessionControl = sessionControl;
        }

        public async Task<IActionResult> MyAuctionsView(string userKey)
        {
            string sessionData = string.Empty;
            sessionData = _sessionControl.GetUserDataFromSession(HttpContext);

            if (userKey != null && userKey != string.Empty)
            {
                await GetBidByUserKeyAsync(userKey);
            }
            if (sessionData != null)
            {
                await GetBidByUserKeyAsync(sessionData);
            }

            return View(_viewModel);
        }

        private async Task GetBidByUserKeyAsync(string userIdentity)
        {
            try
            {
                await SearchBidByUserKeyAsync(userIdentity);
            }
            catch (Exception ex)
            {
                if (ex is IndexOutOfRangeException || ex is FormatException)
                {
                    _viewModel.Message = _message;
                }
                else
                {
                    throw new WepApplicationException("Error occured while bid setting to view model: " + ex.Message);
                }
            }

        }

        private async Task SearchBidByUserKeyAsync(string userIdentity)
        {
            string[] data = userIdentity.Split("/");

            User userBid = null ??
                await _bidRepo.GetBidByFullNameAndDateTimeAsync(data[0], data[1], DateTime.Parse(data[2]));

            if (userBid != null)
            {
                //checks is same bid exists in viewmodel
                User testbid = _viewModel.UserBids
                    .Where(u => u.FirstName == userBid.FirstName)
                    .Where(u => u.LastName == userBid.LastName)
                    .FirstOrDefault(u => u.Bid.BidTime == userBid.Bid.BidTime);

                if (testbid == null)
                {
                    _viewModel.UserBids.Add(userBid);
                    _viewModel.Message = "";
                }
            }
            else
            {
                _viewModel.Message = _message;
            }
        }

    }
}

Bacchus/Bacchus/Views/Shared/Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Bacchus</title>
    <link href="~/bootstrap-v4/css/bootstrap.css" rel="stylesheet" />
    <link href="~/bootstrap-v4/css/bootstrap-grid.css" rel="stylesheet" />
    <link href="~/bootstrap-v4/css/bootstrap-reboot.css" rel="stylesheet" />
    <link href="~/css/style.css" rel="stylesheet" asp-append-version="true" />
</head>
<body>
    <div class="container-fluid">
        <nav class="nav">
            <a class="logo" asp-controller="Home" asp-action="Index">Bacchus</a>
            <div class="nav-menu">
                <a class="nav-item" asp-controller="MyAuctions" asp-action="MyAuctionsView">My auctions</a>
                <a class="nav-item" asp-controller="AuctionResults" asp-action="AuctionResultsView">Ended auctions</a>
            </div>
        </nav>
        @RenderBody()
    </div>
    <footer>
        <p>© 2019 - Bacchus, Olga Suhoverkhaya</p>
    </footer>
    <script src="~/js/jquery-3.3.1.min.js"></script>
    <script src="~/bootstrap-v4/js/bootstrap.js"></script>
    <script src="~/bootstrap-v4/js/bootstrap.bundle.js"></script>
    <script src="~/js/moment.js"></script>
    <script src="~/js/custom-scripts.js" asp-append-version="true"></script>

</body>
</html>